server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081 # 사용자 서비스 주소
          predicates:
            - Path=/api/users/**
          filters:
            - RewritePath=/api/users/(?<segment>.*), /${segment}

        - id: item-service
          uri: http://localhost:8082 # 아이템 서비스 주소
          predicates:
            - Path=/api/items/**
          filters:
            - RewritePath=/api/items/(?<segment>.*), /${segment}

        - id: auth-service
          uri: http://localhost:8083 # 인증 서비스 주소
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /${segment}

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    reactor.netty.http.client: TRACE
